services:
    db:
        image: mysql:8.0
        restart: unless-stopped
        env_file:
            - .env
        command: mysqld --default_time_zone="Asia/Ho_Chi_Minh" --default-authentication-plugin=mysql_native_password
        volumes:
            - ./db:/var/lib/minesql
        ports:
            - "${DB_PORT}:3306"
        environment:
            MYSQL_DATABASE: "${DATABASE}"
            MYSQL_USER: "${USER}"
            MYSQL_ALLOW_EMPTY_PASSWORD: true
            MYSQL_PASSWORD: "${PASSWORD}"
            MYSQL_ROOT_PASSWORD: "${PASSWORD}"
        expose:
            - 3306
    backend:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        env_file:
            - .env
        command: npm run dev
        volumes:
            - .:/app
            - ./uploads:/app/uploads
        ports:
            - "${PORT}:4001"
        depends_on:
            - db
        environment:
            PORT: "${PORT}"
            DB_PORT: "${DB_PORT}"
            HOST: db
            USER: "${USER}"
            PASSWORD: "${PASSWORD}"
            DATABASE: "${DATABASE}"
            NODE_ENV: "${NODE_ENV}"
            JWT_SECRET: "${JWT_SECRET}"
            JWT_EXPIRES_IN: "${JWT_EXPIRES_IN}"
    frontend:
        build:
            context: ../cn_web_frontend
            dockerfile: Dockerfile
        restart: unless-stopped
        ports:
            - 3000:80
        depends_on:
            - backend
        env_file:
            - .env
        environment:
            REACT_APP_END_POINT_IMAGE: backend
